In [ ]:
  #from __future__ import absolute_import, division, print_function, unicode_literals
# !pip uninstall tensorflow-gpu -y
# !pip install tensorflow-gpu==2.0


In [ ]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass


In [ ]:
import tensorflow as tf
print(tf.__version__)

import numpy as np

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

import matplotlib.pyplot as plt


2.3.0


In [ ]:
a=tf.constant(2,name='a')
b=tf.constant(3,name='b')


In [ ]:
x=tf.add(a,b)

In [ ]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
print(x)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
print(x.numpy())

5


In [ ]:
Ve=tf.constant([2,2],name='vec')

In [ ]:
Ve


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
All_one=tf.ones([2,2],np.int32)
All_one_f=tf.ones([2,2],np.float32)

In [ ]:
print(All_one)
print(All_one_f)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
v_a=tf.Variable(2,name='v_a')
v_b=tf.Variable([2,3],name='v_b')
v_c=tf.Variable([[1,2],[3,4]],name='v_c')
v_d=tf.Variable(tf.random.normal([3,4]),name='v_d')

In [ ]:
print(v_a)
print(v_b)
print(v_c)
print(v_d)


<tf.Variable 'v_a:0' shape=() dtype=int32, numpy=2>
<tf.Variable 'v_b:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>
<tf.Variable 'v_c:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'v_d:0' shape=(3, 4) dtype=float32, numpy=
array([[-1.8388474 ,  0.18243489,  1.4366612 , -0.9564651 ],
       [ 1.3697704 , -1.073245  ,  1.88686   ,  0.81094986],
       [-0.4635033 , -0.01576581, -1.6562343 ,  0.16370268]],
      dtype=float32)>


In [ ]:
# v_b.assign(np.array([7,8]))
v_b.assign(([7,8]))
v_b.numpy()
v_b.read_value()

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 8], dtype=int32)>

In [ ]:
print(v_b)
v_e=v_b+[1,1]
#v_b=v_b+1
print(v_e)

<tf.Variable 'v_b:0' shape=(2,) dtype=int32, numpy=array([7, 8], dtype=int32)>
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [ ]:
v_b.assign_add([1,1])
print(v_b)

<tf.Variable 'v_b:0' shape=(2,) dtype=int32, numpy=array([8, 9], dtype=int32)>
